[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "kidpy3"
version = "3.0.0"
dependencies = [
    "matplotlib",
    "h5py",
    "numpy",
    "scipy",
    "pandas",
    "pyserial"
]

[tool.setuptools]
package-dir = {"" = "kidpy3"}